# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/nixos-crypt";
      fsType = "btrfs";
      options = [ "subvol=rootfs" ];
    };

  boot.initrd.luks.devices."nixos-crypt".device = "/dev/disk/by-uuid/5b7fdd99-c6f7-452c-afbb-f848c9f067ac";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4FED-6C76";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/etc" =
    { device = "/dev/mapper/nixos-crypt";
      fsType = "btrfs";
      options = [ "subvol=etc" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/nixos-crypt";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/nixos-crypt";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/opt" =
    { device = "/dev/mapper/nixos-crypt";
      fsType = "btrfs";
      options = [ "subvol=opt" ];
    };

  fileSystems."/partition-root" =
    { device = "/dev/mapper/nixos-crypt";
      fsType = "btrfs";
    };

  fileSystems."/root" =
    { device = "/dev/mapper/nixos-crypt";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/mapper/nixos-crypt";
      fsType = "btrfs";
      options = [ "subvol=tmp" ];
    };

  fileSystems."/var" =
    { device = "/dev/mapper/nixos-crypt";
      fsType = "btrfs";
      options = [ "subvol=var" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
