# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ea330b8d-3c8b-4df8-8a0d-4b307fd30145";
      fsType = "btrfs";
      options = [ "subvol=rootfs" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2A55-D0AC";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/etc" =
    { device = "/dev/disk/by-uuid/ea330b8d-3c8b-4df8-8a0d-4b307fd30145";
      fsType = "btrfs";
      options = [ "subvol=etc" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ea330b8d-3c8b-4df8-8a0d-4b307fd30145";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/ea330b8d-3c8b-4df8-8a0d-4b307fd30145";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/opt" =
    { device = "/dev/disk/by-uuid/ea330b8d-3c8b-4df8-8a0d-4b307fd30145";
      fsType = "btrfs";
      options = [ "subvol=opt" ];
    };

  fileSystems."/partition-root" =
    { device = "/dev/disk/by-uuid/ea330b8d-3c8b-4df8-8a0d-4b307fd30145";
      fsType = "btrfs";
    };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/ea330b8d-3c8b-4df8-8a0d-4b307fd30145";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/steam" =
    { device = "/dev/disk/by-uuid/e86ddaea-4f31-4241-9bba-f3a401f54f92";
      fsType = "btrfs";
      options = [ "subvol=steam" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/ea330b8d-3c8b-4df8-8a0d-4b307fd30145";
      fsType = "btrfs";
      options = [ "subvol=tmp" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/ea330b8d-3c8b-4df8-8a0d-4b307fd30145";
      fsType = "btrfs";
      options = [ "subvol=var" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
