keys:
  - &server_bryxina age1laj5ys9pevm6q64x9507pgvrd3zc86rn9f34k3c7yz880cczh50sj82h86

# Rules are processed top-down, and not well anchored, so put more specific paths first.
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *server_bryxina
