keys:
  - &server_bryxina age1laj5ys9pevm6q64x9507pgvrd3zc86rn9f34k3c7yz880cczh50sj82h86
  - &admin_apinter age1snxzzv973hhufae5ru88qduy0rfk8un407jer2hrgu7hd6d2wpmsc3r3ee

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *server_bryxina
          - *admin_apinter
