# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9ceb3c05-4ac5-4a75-aef7-69ace402338d";
      fsType = "btrfs";
      options = [ "subvol=rootfs" ];
    };

  boot.initrd.luks.devices."nixos-crypt".device = "/dev/disk/by-uuid/6c9f33f7-bd96-485a-a8d3-4855bc97f4c9";
  boot.initrd.luks.devices."Stora0".device = "/dev/disk/by-uuid/4d182351-fad9-44a5-97e0-2ff65b43e620";
  boot.initrd.luks.devices."Stora1".device = "/dev/disk/by-uuid/361a831d-0a17-49b6-9aff-a7c4b609596d";
  boot.initrd.luks.devices."Steam".device = "/dev/disk/by-uuid/ea8b590a-66b9-48eb-8523-18ea94fc29f8";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CC77-66E3";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/etc" =
    { device = "/dev/disk/by-uuid/9ceb3c05-4ac5-4a75-aef7-69ace402338d";
      fsType = "btrfs";
      options = [ "subvol=etc" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/9ceb3c05-4ac5-4a75-aef7-69ace402338d";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/9ceb3c05-4ac5-4a75-aef7-69ace402338d";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/opt" =
    { device = "/dev/disk/by-uuid/9ceb3c05-4ac5-4a75-aef7-69ace402338d";
      fsType = "btrfs";
      options = [ "subvol=opt" ];
    };

  fileSystems."/partition-root" =
    { device = "/dev/disk/by-uuid/9ceb3c05-4ac5-4a75-aef7-69ace402338d";
      fsType = "btrfs";
    };

  fileSystems."/root" =
    { device = "/dev/disk/by-uuid/9ceb3c05-4ac5-4a75-aef7-69ace402338d";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/9ceb3c05-4ac5-4a75-aef7-69ace402338d";
      fsType = "btrfs";
      options = [ "subvol=tmp" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/9ceb3c05-4ac5-4a75-aef7-69ace402338d";
      fsType = "btrfs";
      options = [ "subvol=var" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp35s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}