name: Build flake-updater
on:
  push:
    branches:
      - unstable
  schedule:
    - cron: "0 3 * * *"
  
jobs:
  flake-updater-build:
    name: Build and push image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/unstable'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'unstable'
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            adathor/flake-updater
          tags: |
            type=schedule
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: adathor
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Containerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
