name: Automated Nix flakes update - UNSTABLE
on:
  push:
    branches:
      - unstable
  schedule:
    - cron: '0 8 * * *'

jobs:
  flake-update:
    name: Update flakes for stable
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/unstable'
    container:
        image: docker.io/adathor/flake-updater:latest
        env:
          COMMIT_TOKEN_GITHUB: ${{ secrets.COMMIT_TOKEN_GITHUB }}
    steps:
      - name: Update flakes
        shell: bash
        run: |
            export PATH=/root/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            git clone https://apinter:$COMMIT_TOKEN_GITHUB@github.com/apinter/nix-config -b unstable
            cd nix-config 
            cat flake.nix | grep -i nixpkgs.url
            nix --extra-experimental-features nix-command --extra-experimental-features flakes flake update
      - name: Commit and push
        shell: bash
        run: |
            cd nix-config
            git config --global user.email "adathor+flakes@opensuse.org"
            git config --global user.name "Flake Updater (usntable)"
            git add .
            if git diff --cached --quiet; then
              echo "No changes to commit"
              exit 0
            else
              git commit -m "Automatic flake update"
              git push
            fi
